import type { VideoSource } from '@/lib/types';

export const PREMIUM_SOURCES: VideoSource[] = [
  {
    id: 'ck',
    name: 'CK',
    baseUrl: 'https://www.ckzy1.com/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 1,
    group: 'premium',
  },
  {
    id: 'jkun',
    name: 'jkun',
    baseUrl: 'https://jkunzyapi.com/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 2,
    group: 'premium',
  },
  {
    id: 'souav',
    name: 'souav',
    baseUrl: 'https://api.souavzy.vip/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 3,
    group: 'premium',
  },
  {
    id: '155',
    name: '155',
    baseUrl: 'https://155api.com/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 4,
    group: 'premium',
  },
  {
    id: 'lsb',
    name: 'lsb',
    baseUrl: 'https://apilsbzy1.com/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 5,
    group: 'premium',
  },
  {
    id: 'hsck',
    name: '黄色仓库',
    baseUrl: 'https://hsckzy.vip/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 6,
    group: 'premium',
  },
  {
    id: 'yutu',
    name: '玉兔',
    baseUrl: 'https://yutuzy10.com/api.php/provide/vod',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 7,
    group: 'premium',
  },
  {
    id: 'msnii',
    name: '美少女资源站',
    baseUrl: 'https://www.msnii.com/api/json.php',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 8,
    group: 'premium',
  },
  {
    id: 'xrbsp',
    name: '淫水机资源站',
    baseUrl: 'https://www.xrbsp.com/api/json.php',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 9,
    group: 'premium',
  },
  {
    id: 'gdlsp',
    name: '香奶儿资源站',
    baseUrl: 'https://www.gdlsp.com/api/json.php',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 10,
    group: 'premium',
  },
  {
    id: 'kxgav',
    name: '白嫖资源站',
    baseUrl: 'https://www.kxgav.com/api/json.php',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 11,
    group: 'premium',
  },
  {
    id: 'afasu',
    name: '小湿妹资源站',
    baseUrl: 'https://www.afasu.com/api/json.php',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 12,
    group: 'premium',
  },
  {
    id: 'pgxdy',
    name: '黄AV资源站',
    baseUrl: 'https://www.pgxdy.com/api/json.php',
    searchPath: '',
    detailPath: '',
    enabled: true,
    priority: 13,
    group: 'premium',
  },
];
